apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: goodbye-web
  namespace: goodbye-cpu
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: goodbye-web
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
